Feature/show content
VinayAdaki/OSSE-Assignment-4 pull request #5
Opened 2021-04-15 06:45 UTC by abypunnoose-2020MT93021

** Delete any sections that do not apply **

## Changes

> **Concisely** explain what has changed in this PR. Does your PR require any other PRs to be merged first?  What does a reviewer need to look for? What context will they need?

### How to Test

> Explain the steps to test your PR with enough detail that a person without context will know what to look for. Remember that links are a nice courtesy. Images or animated gifs are even better!

### Code Design

> **If applicable**, add a reference to your code design issue by adding `Resolves #<your code design issue number>`. That will close your code design issue automatically when this PR gets merged.

### User Story / Defect

> **If applicable**, add a link to the user story or defect that this applies to. This will help your reviewer get context.

### Dependencies

> **If applicable**, link to any other PRs that this PR is dependent on. This may be in any repository. This PR should be in WIP until the dependency PR())s get merged.

2021-04-15 12:31 UTC, VinayAdaki commented
Please update the Description Section and remove the sections if not applicable.

2021-04-15 12:33 UTC, VinayAdaki commented on README.md
> +Ide used to make project : Eclipse
```suggestion
IDE used to make project : Eclipse
```

2021-04-15 12:41 UTC, VinayAdaki commented on README.md
> +
if possible please remove extra line

2021-04-15 12:42 UTC, VinayAdaki commented on README.md
> +
above 2 extra lines can be removed

2021-04-15 12:47 UTC, VinayAdaki requested changes
Some comments provided

2021-04-15 15:17 UTC, abypunnoose commented on README.md
> +
Sure, Will do that

2021-04-15 15:18 UTC, abypunnoose commented on README.md
> +
on it.

2021-04-15 15:18 UTC, abypunnoose approved these changes

2021-04-15 15:18 UTC, abypunnoose commented
Approving the changes

2021-04-17 15:08 UTC, VinayAdaki approved these changes

2021-04-17 15:09 UTC, merged